---
- name: Check if OS is supported
  fail:
    msg: "OS not supported for BigBlueButton installation"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_version != "{{ bbb_ubuntu_version }}"

- name: Enable https support for apt
  apt:
    name: apt-transport-https
    state: present
  tags:
    - apt_transport_https

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - update_apt_cache

- name: BigBluebutton required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - software-properties-common
  tags:
    - bbb_dependencies

- name: apt_repository required packages are present
  apt: name=python-apt state=present
  tags:
    - bbb_role_dependencies

- name: Update locale (ensure LANG=en_US.UTF-8)
  lineinfile: dest=/etc/default/locale regexp=^LANG line='LANG=en_US.UTF-8'
  tags:
    - set_locale

- name: Update locale (ensure LC_ALL is absent)
  lineinfile: dest=/etc/default/locale regexp=^LC_ALL state=absent
  tags:
    - set_locale

- name: BigBlueButton apt key is present
  apt_key:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    state: present
  tags:
    - bbb_apt_key

- name: multiverse apt repositories are enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
  tags:
    - multiverse_repositories
    - repositories

- name: BigBlueButton repo is enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb {{ bbb_apt_repo_url }} bigbluebutton-xenial main'
  tags:
    - bbb_repositories
    - repositories

- name: bigbluebutton is installed
  apt: name=bigbluebutton state=present
  tags:
    - install_bbb

- name: bbb-demo is installed
  apt: name=bbb-demo state=present
  tags:
    - install_bbb_demo

- name: bbb-check is installed
  apt: name=bbb-check state=present
  tags:
    - install_bbb_check
- name: Set bbb server name
  command: bbb-conf --setip "{{ bbb_server_name }}"
  tags:
    - run_bbb-conf_setip
- name: Restart bbb
  command: bbb-conf --restart
  tags:
    - run_bbb-conf_restart

