---
- name: Check if OS is supported
  fail:
    msg: "OS not supported for BigBlueButton installation"
  when: ansible_distribution != "Ubuntu" or ansible_distribution_version != "{{ bbb_ubuntu_version }}"

- name: Check if bbb_server_name is defined
  assert:
    that:
      - bbb_server_name != ""
  tags:
    - bbb-check_vars

- name: Enable https support for apt
  apt:
    name: apt-transport-https
    state: present
  tags:
    - apt_transport_https

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - update_apt_cache

- name: Install BigBluebutton required packages
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - software-properties-common
  tags:
    - bbb-dependencies

- name: Check python-apt is present
  apt: name=python-apt state=present
  tags:
    - bbb-role_dependencies

- name: Update locale (ensure LANG=en_US.UTF-8)
  lineinfile: dest=/etc/default/locale regexp=^LANG line='LANG=en_US.UTF-8'
  tags:
    - set_locale

- name: Update locale (ensure LC_ALL is absent)
  lineinfile: dest=/etc/default/locale regexp=^LC_ALL state=absent
  tags:
    - set_locale

- name: Check BigBlueButton apt key is present
  apt_key:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    state: present
  tags:
    - bbb-apt_key

- name: Check multiverse apt repositories are enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
  tags:
    - multiverse_repositories
    - repositories

- name: Check BigBlueButton repo is enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb {{ bbb_apt_repo_url }} bigbluebutton-xenial main'
  tags:
    - bbb-repositories
    - repositories

- name: Check BigBlueButton is installed
  apt: name=bigbluebutton state=present
  tags:
    - install_bbb

- name: Install bbb-demo package
  apt: name=bbb-demo state=present
  when: bbb_install_demo == True
  tags:
    - install_bbb-demo

- name: Install bbb-check package
  apt: name=bbb-check state=present
  when: bbb_install_check == True
  tags:
    - install_bbb-check

- name: Set BigBlueButton server name
  command: bbb-conf --setip "{{ bbb_server_name }}"
  tags:
    - run_bbb-conf_setip

- name: Get server local IP address
  debug: msg="{{ ansible_default_ipv4.address }}"
  register: server_ip
  tags:
    - bbb-get_local_ip
# - name: Print local IP address
#   debug: msg="{{ server_ip }}"
#   tags:
#     - bbb-get_local_ip

- name: Get server public IP address
  ipify_facts:
  register: public_ip
  tags:
    - bbb-get_public_ip

- name: Get server public IP address
  debug: msg="{{ public_ip.ansible_facts.ipify_public_ip }}"
  register: public_ip
  tags:
    - bbb-get_public_ip

- name: Print server public IP address
  debug: msg="{{ public_ip }}"
  tags:
    - bbb-get_public_ip


- name: Verify local IP vs public IP addresses
  debug: msg="{{ server_ip }}"
  register: internal_ip
  when: server_ip != public_ip
  tags:
    - bbb-check_server_ip

- name: Verify local IP vs public IP addresses
  debug: msg="{{ public_ip }}"
  register: server_ip
  when: server_ip != public_ip
  tags:
    - bbb-check_server_ip

# BigBlueButton NAT configuration
- include_tasks: nat.yml
  when: bbb_configure_nat == True and internal_ip is defined
# BigBlueButton SSL configuration
- include_tasks: letsencrypt.yml
  when: bbb_configure_ssl == True
- include_tasks: ssl.yml
  when: bbb_configure_ssl == True

- name: Restart BigBlueButton
  command: bbb-conf --restart
  tags:
    - bbb-restart

- name: Check BigBlueButton installation
  command: bbb-conf --check
  register: bbb_check_out
  tags:
    - bbb-check_install
- name: bbb-conf --check output
  debug: msg="{{ bbb_check_out }}"
  tags:
    - bbb-check_install
